### ISSUE TITLE
Include a section on updating packages and R

### ISSUE THREAD

**Issue by boshek** [bcgov/ds-cop-intro-to-r#12]
Rationale: folks are going to encounter this. A gentle introduction might be useful.

**Comment by ateucher** [comment]
Related: reinforce the difference between installing and loading packages (i.e., don't start your scripts with`install.packages()`)

**Comment by boshek** [comment]
To consider: any mention of installing from github?

**Comment by ateucher** [comment]
Tough one. There are quite a few bcgov packages on github only, so useful, but don't want to overburden them

**Comment by stephhazlitt** [comment]
I think we should ground content to the novice learner -- so with that in mind would focus on `install.packages()` only. 2 cents 💸
